#   Copyright 2021 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: sso-authc-info
  namespace: exastro-days-tokyo
data:
  GOOGLE_CLIENT_ID: ""
  GITHUB_CLIENT_ID: ""
  TWITTER_CLIENT_ID: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: session-manage-info
  namespace: exastro-days-tokyo
data:
  SECRET_KEY: "" # If empty, generate random secret. (secrets.token_hex(16))
  REDIS_URL: "redis://session-db:6379"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-container-info
  namespace: exastro-days-tokyo
data:
  EVENT_PROTOCOL: "http"
  EVENT_HOST: "event-user"
  EVENT_PORT: "8080"
  SPERKER_PROTOCOL: "http"
  SPERKER_HOST: "speaker-user"
  SPERKER_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-user
  namespace: exastro-days-tokyo
spec:
  selector:
    matchLabels:
      name: front-user
  replicas: 1
  template:
    metadata:
      labels:
        name: front-user
    spec:
      containers:
      - name: front-user
        image: exastro/exastro-days-tokyo-front-user:0.0.1_20220124_1645
        envFrom:
        - prefix: SERVICE_
          configMapRef:
            name: service-container-info
        - prefix: SSO_
          configMapRef:
            name: sso-authc-info
        - configMapRef:
            name: session-manage-info
        env:
        - name: LC_ALL
          value: C.UTF-8
        - name: LANG
          value: C.UTF-8
        - name: PYTHONIOENCODING
          value: utf-8

---
apiVersion: v1
kind: Service
metadata:
  name: front-user
  labels:
    name: front-user
  namespace: exastro-days-tokyo
spec:
  type: NodePort
  ports:
  - name: flask
    port: 5000
    targetPort: 5000
    nodePort: 31443
  selector:
    name: front-user
