apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    nodePort: 30300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9090'
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: prometheus
      containers:
        - image: prom/prometheus
          name: prometheus
          args: [ "--storage.tsdb.path=/prometheus-data", "--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.no-lockfile" ]
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: prometheus-persistent-storage
              mountPath: /prometheus-data
      volumes:
        - name: config
          configMap:
            name: prometheus
        - name: prometheus-persistent-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
