apiVersion: v1
kind: Service
metadata:
  name: jaeger-query-nodeport
  namespace: exastro-days-tokyo
spec:
  type: NodePort
  ports:
  - name: query
    nodePort: 30880
    port: 16686
    targetPort: 16686
  selector:
    app: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: jaeger-all-in-one-inmemory
    app.kubernetes.io/managed-by: jaeger-operator
    app.kubernetes.io/name: jaeger-all-in-one-inmemory
    app.kubernetes.io/part-of: jaeger
